.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.0_curve=bezier.txt 0 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.25_curve=bezier.txt 0 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.5_curve=bezier.txt 0 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.75_curve=bezier.txt 0 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=1.0_curve=bezier.txt 0 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.0_curve=bezier.txt 1 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.25_curve=bezier.txt 1 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.5_curve=bezier.txt 1 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.75_curve=bezier.txt 1 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=1.0_curve=bezier.txt 1 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.0_curve=bezier.txt 1 3
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.25_curve=bezier.txt 1 3
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.5_curve=bezier.txt 1 3
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.75_curve=bezier.txt 1 3
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=1.0_curve=bezier.txt 1 3
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.0_curve=bezier.txt 2 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.25_curve=bezier.txt 2 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.5_curve=bezier.txt 2 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=0.75_curve=bezier.txt 2 0
.\\quadTree.exe ./data/empty.txt -1 ./data/insert_s=1.0_curve=bezier.txt 2 0